#ifndef __TASK_LIST_IF_H__
#define __TASK_LIST_IF_H__

enum {
	/* APP TASKS */
	SL_TASK_SHELL_ID = 1,
	SL_TASK_LIFE_ID,
	SL_TASK_SENSOR_ID,
	SL_TASK_POP_CTRL_ID,
	SL_TASK_DEV_CTRL_ID,
	SL_TASK_IO_CTRL_ID,
	SL_TASK_IF_ID,
	SL_TASK_CPU_SERIAL_IF_ID,
	SL_TASK_SM_ID,
	SL_TASK_FIRMWARE_ID,
	SL_TASK_RS485_MODBUS_ID,
	SL_TASK_DBG_ID,
	/* EOT task ID */
};


enum {
	GU_TASK_TIMER_ID,
	GU_TASK_IF_CONSOLE_ID,
	GU_TASK_CONSOLE_ID,
	GU_TASK_IF_ID,
	GU_TASK_DEBUG_MSG_ID,
	GU_TASK_IF_APP_ID,
	GU_TASK_FIRMWARE_ID,
	GU_TASK_CTRL_POP_ID,
	GU_TASK_LIST_LEN
};


#endif //__TASK_LIST_IF_H__
