#!/bin/bash
if [ "$1" = "-g" ]
then
echo .1.3.6.1.2.1.25.1.2.5.3
echo gauge
IN_FILE="/run/fpt_gateway/snmp/sl_sensors.txt"
VALUE=$(/bin/cat $IN_FILE | /usr/bin/awk 'FNR == 33 {print}')
echo $VALUE
fi
exit 0
